# Workflow for deploying static content to Cloudflare Pages
name: Deploy static content to Cloudflare Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets necessary permissions
permissions:
  contents: read

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: cloudflare-pages
      # Use the URL from Cloudflare deployment
      url: ${{ steps.cloudflare-deployment.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Create artifact for reference, without GitHub Pages dependency
      - name: Archive website content
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-pages
          path: '.'
      
      - name: Deploy to Cloudflare Pages
        id: cloudflare-deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Usa el nombre del repositorio en lugar de "blog"
          command: pages deploy . --project-name=${{ github.repository_name || github.event.repository.name }}
